-- workspace-resolve.ts now addresses a workspace by (owner, repo, branch)
-- instead of an opaque workspace_id a chat client cannot be trusted to carry
-- across turns. This index is what makes that lookup cheap: listSlotOccupants
-- selects repository and current_branch, and resolution filters on them.
--
-- It is deliberately NOT UNIQUE, and that is a correction rather than a
-- preference. The first version of this migration created a partial UNIQUE
-- index on these columns, on the assumption that two live workspaces sharing a
-- repository and branch was a race that had not happened yet. Applying it to
-- production failed:
--
--   UNIQUE constraint failed: workspaces.tenant_id, workspaces.repository,
--   workspaces.current_branch
--
-- because it is not hypothetical. timc0y/EasyRoads has three workspaces on
-- forge/3adc07ad3283ce46, every one of them in state 'ready' — the same "three
-- workspaces open and every call ambiguous" failure that motivated addressing
-- by branch in the first place, still sitting in the data. A second pair sits
-- on current_branch 'main', meaning those two never had a forge branch cut at
-- all.
--
-- Enforcing uniqueness therefore requires deciding what becomes of those rows,
-- and destroying somebody's ready workspaces as a side effect of a schema
-- migration is not a decision a migration should make quietly. The ambiguity is
-- already handled where an agent can see it: workspace-resolve.ts refuses a
-- multi-match and names the candidates as "owner/repo on branch", so nothing
-- acts on the wrong workspace in the meantime.
--
-- To enforce it later: reconcile the duplicates first, then add the partial
-- UNIQUE index in a follow-up migration, its WHERE clause matching the
-- TERMINAL_STATES list in apps/forge-edge-gateway/src/capacity.ts. Partial
-- indexes themselves are fine on D1 — 0018_credential_profiles.sql already
-- relies on one — so the blocker is the data, not the syntax.
CREATE INDEX IF NOT EXISTS idx_workspaces_tenant_repo_branch
  ON workspaces (tenant_id, repository, current_branch);
