import { registerAppResource, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

export const FORGE_CONSOLE_URI = 'ui://forge/workspace-console';

const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark;font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;--ink:#171717;--muted:#666;--line:#d8d8d8;--surface:#fff;--soft:#f4f4f4;--accent:#176b45}*{box-sizing:border-box}body{margin:0;background:var(--surface);color:var(--ink)}main{padding:18px;max-width:760px}header{display:flex;align-items:center;justify-content:space-between;gap:16px;border-bottom:1px solid var(--line);padding-bottom:14px}.brand{font-weight:750;letter-spacing:-.02em}.status{font-size:13px;color:var(--muted)}h2{font-size:15px;margin:18px 0 8px}.summary{font-size:14px;line-height:1.55;max-width:68ch}.facts{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.fact{background:var(--soft);border-radius:8px;padding:7px 9px;font-size:12px}.profiles{display:grid;gap:8px;margin-top:12px}.profile{display:flex;align-items:center;justify-content:space-between;gap:12px;border:1px solid var(--line);border-radius:8px;padding:10px 12px;font-size:13px}.profile-name{font-weight:700}.profile-meta{color:var(--muted);font-size:12px}.badge{border-radius:999px;background:var(--soft);padding:3px 7px;font-size:11px;font-variant-numeric:tabular-nums}.badge.valid{background:#dff5e8;color:#075c35}.badge.invalid{background:#fae2e2;color:#8d1717}.empty{padding:18px 0;color:var(--muted);font-size:14px}.shots{display:flex;gap:10px;overflow:auto}.shots img{display:block;max-height:220px;max-width:320px;border-radius:10px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}button{font:inherit;border:0;border-radius:8px;padding:9px 12px;background:var(--accent);color:white;font-weight:650}button.secondary{background:var(--soft);color:var(--ink)}@media(prefers-color-scheme:dark){:root{--ink:#f5f5f5;--muted:#aaa;--line:#3a3a3a;--surface:#171717;--soft:#282828;--accent:#59c18d}.badge.valid{background:#173f2a;color:#9fe6bd}.badge.invalid{background:#4b2020;color:#ffb3b3}}@media(prefers-reduced-motion:no-preference){main{animation:appear .18s ease-out}@keyframes appear{from{opacity:.6;transform:translateY(3px)}}}
</style></head><body><main><header><div class="brand">Forge</div><div class="status" id="status">Ready to build</div></header><div id="content"><div class="empty">Choose a repository, review a live URL, or ask ChatGPT to build and test a change. Forge will use the cheapest capable runtime.</div></div></main><script>
const content=document.querySelector('#content'),status=document.querySelector('#status');
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(value){if(!value||typeof value!=='object')return;const mode=value.executionMode||value.execution_mode;const evidence=Array.isArray(value.evidence)?value.evidence:[];const profiles=Array.isArray(value.profiles)?value.profiles:(value.profile?[value.profile]:[]);const repo=value.repository||(value.repository?.owner?value.repository.owner+'/'+value.repository.name:null);status.textContent=profiles.length?'Credential profiles':(value.state||mode||'Ready');let facts=[];if(repo)facts.push(['Repository',repo]);if(value.workspace_id||value.workspaceId)facts.push(['Workspace',value.workspace_id||value.workspaceId]);if(mode)facts.push(['Mode',String(mode).replaceAll('_',' ')]);if(value.containerUsed===false)facts.push(['Compute','No container']);if(evidence.length)facts.push(['Screenshots',evidence.length]);const profileHtml=profiles.length?'<h2>Credential profiles</h2><div class="profiles">'+profiles.map(profile=>'<div class="profile"><div><div class="profile-name">'+esc(profile.name)+'</div><div class="profile-meta">'+esc(profile.provider)+' · '+esc(profile.active?'active':'available')+'</div></div><span class="badge '+esc(profile.state)+'">'+esc(profile.state)+'</span></div>').join('')+'</div>':'';content.innerHTML='<p class="summary">'+esc(value.nextStep||value.next_step||value.message||'Forge is ready for the next instruction.')+'</p><div class="facts">'+facts.map(([a,b])=>'<span class="fact">'+esc(a)+': <strong>'+esc(b)+'</strong></span>').join('')+'</div>'+profileHtml+(evidence.length?'<h2>Parallax evidence</h2><p class="summary">Screenshots are attached to the tool result for direct visual inspection.</p>':'')+'<div class="actions"><button data-message="List my Forge credential profiles and show their validation state.">Manage credentials</button><button class="secondary" data-message="Reconcile the current Forge workspace and report whether the latest commit is pushed.">Reconcile workspace</button></div>';}
window.addEventListener('message',event=>{const m=event.data;if(m?.method==='ui/notifications/tool-result')render(m.params?.structuredContent||m.params?.content);if(m?.method==='ui/notifications/tool-input')status.textContent='Working…'});document.addEventListener('click',e=>{const message=e.target?.dataset?.message;if(message)parent.postMessage({jsonrpc:'2.0',id:crypto.randomUUID(),method:'ui/message',params:{role:'user',content:[{type:'text',text:message}]}},'*')});parent.postMessage({jsonrpc:'2.0',id:'forge-init',method:'ui/initialize',params:{appInfo:{name:'Forge Console',version:'0.1.0'},appCapabilities:{},protocolVersion:'2026-01-26'}},'*');
</script></body></html>`;

export function registerForgeConsole(server: McpServer): void {
  registerAppResource(server, 'Forge Console', FORGE_CONSOLE_URI, {
    description: 'Workspace, screenshot evidence, changes and approval state for Forge tasks.',
    _meta: { ui: { prefersBorder: true } }
  }, async () => ({
    contents: [{ uri: FORGE_CONSOLE_URI, mimeType: RESOURCE_MIME_TYPE, text: html, _meta: { ui: { prefersBorder: true } } }]
  }));
}
