import { z, type ZodRawShape } from 'zod';

const workspaceId = z.string().regex(/^ws_[0-9a-hjkmnp-tv-z]{20,32}$/);
const revision = z.number().int().positive().optional();
const idempotency = z.string().min(8).max(200);
const repository = z.object({ provider: z.literal('github'), owner: z.string().min(1).max(100), name: z.string().min(1).max(100) });
const cwd = z.string().startsWith('/workspace').default('/workspace/repo');
const credentialProfileId = z.string().regex(/^crp_[0-9a-hjkmnp-tv-z]{20,32}$/);
const credentialMetadata = z.object({ account_id: z.string().regex(/^[a-f0-9]{32}$/i).optional() }).default({});

export interface ForgeToolDefinition<TShape extends ZodRawShape = ZodRawShape> {
  name: string;
  title: string;
  description: string;
  inputSchema: TShape;
  sideEffect: 'none' | 'workspace' | 'external' | 'destructive';
  approval: 'none' | 'policy' | 'required';
}

export type ForgeMcpContent =
  | { type: 'text'; text: string }
  | { type: 'image'; data: string; mimeType: string };

export interface ForgeToolResponse {
  kind: 'forge_tool_response';
  value: Record<string, unknown>;
  content: ForgeMcpContent[];
}

export function forgeToolResponse(
  value: Record<string, unknown>,
  content: ForgeMcpContent[]
): ForgeToolResponse {
  return { kind: 'forge_tool_response', value, content };
}

export const forgeTools = [
  { name: 'forge_capabilities', title: 'Get Forge capability manifest', description: 'Return the stable repository, workspace, Git, recovery, browser, deployment, and approval capabilities available to this MCP session.', inputSchema: {}, sideEffect: 'none', approval: 'none' },
  { name: 'forge_credential_list', title: 'List credential profiles', description: 'List the tenant credential profiles. Secrets and encrypted payloads are never returned.', inputSchema: {}, sideEffect: 'none', approval: 'none' },
  { name: 'forge_credential_create', title: 'Create credential profile', description: 'Encrypt and store a Cloudflare API token as a named tenant profile. The secret is never returned or logged.', inputSchema: { name: z.string().min(1).max(100), provider: z.literal('cloudflare'), secret: z.string().min(16).max(4096), metadata: credentialMetadata, make_active: z.boolean().default(false) }, sideEffect: 'external', approval: 'none' },
  { name: 'forge_credential_update', title: 'Update credential profile', description: 'Rename, replace, or update the metadata of a credential profile. Replacing a secret resets validation state.', inputSchema: { credential_profile_id: credentialProfileId, name: z.string().min(1).max(100).optional(), secret: z.string().min(16).max(4096).optional(), metadata: credentialMetadata.optional(), make_active: z.boolean().optional() }, sideEffect: 'external', approval: 'none' },
  { name: 'forge_credential_delete', title: 'Delete credential profile', description: 'Permanently delete a tenant credential profile.', inputSchema: { credential_profile_id: credentialProfileId }, sideEffect: 'destructive', approval: 'none' },
  { name: 'forge_credential_switch', title: 'Switch credential profile', description: 'Select a profile for this MCP session and mark it active for the tenant.', inputSchema: { credential_profile_id: credentialProfileId }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_credential_validate', title: 'Validate credential profile', description: 'Decrypt a profile only for its provider validation request, then persist its validation state.', inputSchema: { credential_profile_id: credentialProfileId }, sideEffect: 'external', approval: 'none' },
  { name: 'forge_workspace_reconcile', title: 'Reconcile workspace recovery state', description: 'Read the checked-out Git state, reconcile durable metadata, and report whether the current Forge commit has been pushed.', inputSchema: { workspace_id: workspaceId }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_workspace_prove', title: 'Prove workspace state', description: 'Produce one evidence receipt from the actual checkout: immutable base, branch, HEAD, changed paths, filesystem and HEAD file hashes, worktree hash, committed outgoing hash, and recorded-state divergence.', inputSchema: { workspace_id: workspaceId }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_workspace_checkpoint', title: 'Create durable workspace checkpoint', description: 'Create a provider snapshot containing the workspace filesystem and Git data before a risky operation. The checkpoint is retained independently from the active session.', inputSchema: { workspace_id: workspaceId, name: z.string().min(1).max(120).optional() }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_workspace_restore', title: 'Restore durable workspace checkpoint', description: 'Restore a recorded provider checkpoint into this workspace. Forge blocks restoration over dirty or unpushed work so recovery cannot silently discard a newer change.', inputSchema: { workspace_id: workspaceId, snapshot_id: z.string().startsWith('snap_'), expected_revision: revision }, sideEffect: 'destructive', approval: 'none' },
  { name: 'forge_work_export', title: 'Export recoverable work', description: 'Persist an evidence-backed recovery bundle to Forge artifacts before risky Git, session, or teardown operations. The export contains committed and uncommitted binary diffs plus a base64 tar.gz archive of all untracked files.', inputSchema: { workspace_id: workspaceId, max_bytes: z.number().int().min(1000).max(4000000).default(3000000) }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_cloudflare_deploy', title: 'Deploy with Cloudflare Wrangler', description: 'Deploy the workspace with pnpm exec wrangler using the selected Cloudflare profile for this one approved command. The API token is redacted from all results and is never persisted in the sandbox.', inputSchema: { workspace_id: workspaceId, credential_profile_id: credentialProfileId.optional(), environment: z.string().regex(/^[A-Za-z0-9_-]{1,64}$/).optional(), config_path: z.string().startsWith('/workspace/repo/').max(500).refine((value) => !value.split('/').includes('..') && !value.includes('\0')).optional(), approval_id: z.string().startsWith('apr_').optional(), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'external', approval: 'required' },
  { name: 'forge_repository_list', title: 'List authorized repositories', description: 'List GitHub repositories currently authorized through the Forge GitHub App for this account.', inputSchema: {}, sideEffect: 'none', approval: 'none' },
  { name: 'forge_review', title: 'Review a site with Parallax', description: 'The easiest and cheapest Forge path. Capture screenshot and accessibility evidence from an existing URL without starting a container, ready for a strict Parallax review.', inputSchema: { url: z.string().url(), captures: z.array(z.object({ selection: z.string().min(1).max(200), path: z.string().startsWith('/'), state: z.string().min(1).max(100).default('entry') })).min(1).max(10), viewports: z.array(z.object({ id: z.string().min(1).max(40), width: z.number().int().min(240).max(1920), height: z.number().int().min(320).max(2160) })).min(1).max(2).default([{ id: 'phone', width: 390, height: 844 }, { id: 'desktop', width: 1440, height: 900 }]), full_page: z.boolean().default(false) }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_workspace_create', title: 'Create Forge workspace', description: 'Create a disposable isolated workspace from an authorized repository. Forge verifies the requested runtime before reporting provisioning success; the maintained Sandbox image defaults to Node 24.', inputSchema: { repository, ref: z.string().default('main'), runtime: z.enum(['node-22','node-24','python-3.13','general-purpose']).default('node-24'), persistence: z.literal('ephemeral').default('ephemeral'), bootstrap: z.boolean().default(true), idempotency_key: idempotency }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_workspace_get', title: 'Get Forge workspace', description: 'Return lifecycle, repository, revision, processes, previews, snapshot and outstanding state for one workspace.', inputSchema: { workspace_id: workspaceId }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_files_tree', title: 'List workspace files', description: 'Return a bounded, Git-aware file tree rooted inside /workspace.', inputSchema: { workspace_id: workspaceId, path: z.string().startsWith('/workspace').default('/workspace/repo'), depth: z.number().int().min(1).max(20).default(4), limit: z.number().int().min(1).max(10000).default(1000) }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_files_read', title: 'Read workspace file', description: 'Read a bounded text range with a content hash for conflict-safe edits.', inputSchema: { workspace_id: workspaceId, path: z.string().startsWith('/workspace'), start_line: z.number().int().positive().optional(), end_line: z.number().int().positive().optional(), max_bytes: z.number().int().min(1).max(500000).default(200000) }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_files_write', title: 'Write workspace file', description: 'Atomically replace one workspace file, then re-read it from the same filesystem before acknowledging success. Returns previous and resulting hashes, workspace revision, and worktree hash.', inputSchema: { workspace_id: workspaceId, path: z.string().startsWith('/workspace/repo/').max(1000), content: z.string().max(4000000), expected_sha256: z.string().regex(/^[a-f0-9]{64}$/).optional(), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_files_patch', title: 'Apply file patch', description: 'Apply a unified diff inside the repository. Requires an idempotency key and optional expected workspace revision.', inputSchema: { workspace_id: workspaceId, patch: z.string().min(1).max(1000000), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_shell_exec', title: 'Execute bounded command', description: 'Execute a foreground command in an explicit directory with timeout, output and network-policy bounds. Risky commands return a real user approval URL.', inputSchema: { workspace_id: workspaceId, command: z.string().min(1).max(16384), cwd, timeout_ms: z.number().int().min(100).max(900000).default(300000), environment: z.record(z.string(), z.string()).default({}), network_policy: z.enum(['deny_all','package_install','development','custom_allowlist','unrestricted_with_approval']).default('development'), output_limit_bytes: z.number().int().min(1000).max(1000000).default(200000), expected_revision: revision, idempotency_key: idempotency, approval_id: z.string().startsWith('apr_').optional() }, sideEffect: 'workspace', approval: 'policy' },
  { name: 'forge_process_start', title: 'Start background process', description: 'Start a long-running process such as a development server and return a Forge process identifier immediately.', inputSchema: { workspace_id: workspaceId, command: z.string().min(1).max(16384), cwd, environment: z.record(z.string(), z.string()).default({}), network_policy: z.enum(['deny_all','package_install','development','custom_allowlist']).default('development'), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'workspace', approval: 'policy' },
  { name: 'forge_process_logs', title: 'Read process logs', description: 'Read a bounded process-log page using an opaque cursor.', inputSchema: { workspace_id: workspaceId, process_id: z.string().startsWith('proc_'), cursor: z.string().optional() }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_process_get', title: 'Get managed process status', description: 'Read the actual managed process status, command, working directory, and PID for one workspace-owned process.', inputSchema: { workspace_id: workspaceId, process_id: z.string().startsWith('proc_') }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_process_stop', title: 'Stop managed process', description: 'Stop one workspace-owned managed process. This never selects a host process by port or name.', inputSchema: { workspace_id: workspaceId, process_id: z.string().startsWith('proc_'), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_check_start', title: 'Start durable workspace check', description: 'Start a long-running validation command as a managed workspace check. Returns immediately with a process ID, commit, and durable log/status handle instead of relying on a foreground response timeout.', inputSchema: { workspace_id: workspaceId, name: z.string().min(1).max(100), command: z.string().min(1).max(16384), cwd, environment: z.record(z.string(), z.string()).default({}), network_policy: z.enum(['deny_all','package_install','development','custom_allowlist']).default('development'), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'workspace', approval: 'policy' },
  { name: 'forge_check_get', title: 'Get workspace check', description: 'Read the current status, command, commit, and process details for a managed validation check.', inputSchema: { workspace_id: workspaceId, process_id: z.string().startsWith('proc_') }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_check_cancel', title: 'Cancel workspace check', description: 'Cancel a managed validation check and persist that cancellation as a workspace mutation.', inputSchema: { workspace_id: workspaceId, process_id: z.string().startsWith('proc_'), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_git_status', title: 'Read Git status', description: 'Return structured working-tree and branch status for the workspace repository.', inputSchema: { workspace_id: workspaceId }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_git_diff', title: 'Read Git diff', description: 'Return a bounded unified diff for the working tree or staged changes.', inputSchema: { workspace_id: workspaceId, staged: z.boolean().default(false) }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_git_branch_create', title: 'Create Forge branch', description: 'Create and check out a local branch under the required forge/ namespace.', inputSchema: { workspace_id: workspaceId, branch: z.string().startsWith('forge/').max(107), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_git_commit', title: 'Commit workspace changes', description: 'Stage selected repository paths and create a commit attributed to forge-mcp[bot].', inputSchema: { workspace_id: workspaceId, message: z.string().min(1).max(500), paths: z.array(z.string().min(1).max(500)).max(100).default([]), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_git_outgoing_diff', title: 'Inspect outgoing Git change', description: 'Return the exact bounded diff and hash between the base branch and current Forge branch before approval.', inputSchema: { workspace_id: workspaceId, base: z.string().min(1).max(255).default('main') }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_git_push', title: 'Push Forge branch', description: 'Push a non-default forge/ branch through the GitHub App credential proxy. A real user approval page is required.', inputSchema: { workspace_id: workspaceId, branch: z.string().startsWith('forge/').max(107), base: z.string().min(1).max(255).default('main'), expected_diff_hash: z.string().regex(/^[a-f0-9]{64}$/), approval_id: z.string().startsWith('apr_').optional(), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'external', approval: 'required' },
  { name: 'forge_pull_request_create', title: 'Create draft pull request', description: 'Create a draft GitHub pull request for an already pushed Forge branch. A real user approval page is required.', inputSchema: { workspace_id: workspaceId, head: z.string().startsWith('forge/').max(107), base: z.string().min(1).max(255).default('main'), title: z.string().min(1).max(256), body: z.string().max(60000).default(''), approval_id: z.string().startsWith('apr_').optional() }, sideEffect: 'external', approval: 'required' },
  { name: 'forge_preview_expose', title: 'Expose private preview', description: 'Expose a running process through a short-lived Forge preview capability. Private is the default; public requires approval.', inputSchema: { workspace_id: workspaceId, process_id: z.string().startsWith('proc_'), port: z.number().int().min(1024).max(65535), access: z.enum(['private','tenant','share-link','public']).default('private'), ttl_seconds: z.number().int().min(60).max(86400).default(3600), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'workspace', approval: 'policy' },
  { name: 'forge_review_capture', title: 'Capture Parallax review evidence', description: 'Capture a versioned Parallax evidence packet for bounded selections, routes, states and viewports. Use forge_artifact_get to inspect each stored screenshot image.', inputSchema: { workspace_id: workspaceId, preview_id: z.string().startsWith('prv_'), captures: z.array(z.object({ selection: z.string().min(1).max(200), route: z.string().startsWith('/'), state: z.string().min(1).max(100).default('entry') })).min(1).max(20), viewports: z.array(z.object({ id: z.string().min(1).max(40), width: z.number().int().min(240).max(3840), height: z.number().int().min(240).max(2160) })).min(1).max(4) }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_browser_screenshot', title: 'Capture browser screenshot', description: 'Capture browser evidence from a Forge preview and persist it as an artifact bound to workspace revision and viewport.', inputSchema: { workspace_id: workspaceId, preview_id: z.string().startsWith('prv_'), path: z.string().startsWith('/').default('/'), viewport: z.object({ width: z.number().int().min(240).max(3840), height: z.number().int().min(240).max(2160) }), full_page: z.boolean().default(true) }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_browser_accessibility_tree', title: 'Read browser accessibility tree', description: 'Capture the bounded accessibility tree for a Forge preview route at a selected viewport.', inputSchema: { workspace_id: workspaceId, preview_id: z.string().startsWith('prv_'), path: z.string().startsWith('/').default('/'), viewport: z.object({ width: z.number().int().min(240).max(3840), height: z.number().int().min(240).max(2160) }) }, sideEffect: 'workspace', approval: 'none' },
  { name: 'forge_artifact_get', title: 'Get browser artifact', description: 'Return a stored Forge artifact to the MCP client. Image artifacts are returned as MCP image content for direct model inspection.', inputSchema: { workspace_id: workspaceId, artifact_id: z.string().startsWith('art_'), max_bytes: z.number().int().min(1).max(4000000).default(2500000) }, sideEffect: 'none', approval: 'none' },
  { name: 'forge_workspace_destroy', title: 'Destroy Forge workspace', description: 'Revoke previews and capabilities, stop processes, destroy the sandbox and mark the workspace destroyed.', inputSchema: { workspace_id: workspaceId, preserve_artifacts: z.boolean().default(true), expected_revision: revision, idempotency_key: idempotency }, sideEffect: 'destructive', approval: 'policy' }
] as const satisfies readonly ForgeToolDefinition[];

export type ForgeToolName = typeof forgeTools[number]['name'];
export type ForgeToolHandler = (input: Record<string, unknown>) => Promise<Record<string, unknown> | ForgeToolResponse>;
export type ForgeToolHandlers = Record<ForgeToolName, ForgeToolHandler>;

export interface ForgeMcpAdapter {
  registerTool(definition: ForgeToolDefinition, handler: ForgeToolHandler): void;
  connect(request: Request, context: { subject: string; tenantId: string }): Promise<Response>;
}
